name: Write .env file

on:
  workflow_dispatch:
  push:
    branches:
      - feature/user_modal_dalog

jobs:
  write-env:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file with secrets and vars
        run: |
          echo "REDIS_HOST=${{ vars.REDIS_HOST }}" > .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Fetch environment secrets names
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Kusmarius/test-fe/environments/develop/secrets \
          | jq -r '.secrets[] | "\(.name)"' >> .sec

      - name: Show created .env content
        run: cat .env

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
