name: Write .env file

on:
  workflow_dispatch:
  push:
    branches:
      - feature/user_modal_dalog

jobs:
  write-env:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file with secrets and vars
        run: |
          echo "REDIS_HOST=${{ vars.REDIS_HOST }}" > .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Show created .env content
        run: cat .env

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
