name: Show Environment 1

on:
  workflow_dispatch:
  push:
    branches:
      - feature/user_modal_dalog

jobs:
  show-env:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Show environment variable REDIS_HOST
        run: echo "REDIS_HOST is: ${{ vars.REDIS_HOST }}"

      - name: Show environment name and Redis secrets
        run: |
          echo "This job is running in environment: develop"
          echo "REDIS_PASSWORD is: $REDIS_PASSWORD"

