name: Write .env file

on:
  workflow_dispatch:
  push:
    branches:
      - feature/user_modal_dalog

jobs:
  write-env:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch environment variables
        run: |
          curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/environments/develop/variables | \
          jq -r '.variables[] | "\(.name)=\(.value)"' > .env

      - name: Fetch environment secrets names
        run: |
          curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/environments/develop/secrets \
          | jq -r '.secrets[] | "\(.name)"' >> .sec


      - name: Show created .env content
        run: cat .env

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
